import Head from "next/head";
import { Container, Stack, Box } from "@mui/material";
export default function Blog() {
  return (
    <>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fixed>
        <Stack>
          <Box
            sx={{
              width: "full",
              height: "35rem",
              background: "gray",
              borderRadius: "12px",
            }}
          ></Box>
        </Stack>
      </Container>
    </>
  );
}
