import Head from "next/head";
import { useRef } from "react";
import { Stack, Box, Container, Typography, Button } from "@mui/material";

export default function Home() {
  const experienceRef = useRef(null);

  const scrollInto = (ref) => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };
  return (
    <>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack
        sx={{
          width: "100vw",
          height: "100vh",
          position: "static",
          background: "#12486B",
          top: 0,
        }}
      >
        <Container maxWidth="xl">
          <Button onClick={() => scrollInto(experienceRef)}>scroll</Button>
        </Container>
      </Stack>
      <Stack
        sx={{
          background: "#F6F6F7",
        }}
      >
        <Container maxWidth="xl">
          <Box
            display="flex"
            alignItems="center"
            justifyContent="center"
            marginY={2}
          >
            <Typography variant="h2" color="#181A2A">
              Experience
            </Typography>
          </Box>
        </Container>
      </Stack>
      <Box
        ref={experienceRef}
        sx={{
          width: "100vw",
          height: "100vh",
          background: "#419197",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Typography variant="h1">Tian Memeg</Typography>
      </Box>
      <Box
        sx={{
          width: "100vw",
          height: "100vh",
          background: "gray",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Typography variant="h1">MEMEG</Typography>
      </Box>
    </>
  );
}
